export const keywords: string[] = [
  "huis snel verkopen",
  "huis verkopen",
  "huis verkopen bij scheiding",
  "huis verkopen met restschuld",
  "huis verkopen bij schulden",
  "huis verkopen na overlijden",
  "huis verkopen zonder makelaar",
  "woning verkopen zonder makelaar",
  "huis verkopen particulier",
  "woning snel verkopen",
  "huis verkopen met spoed",
  "huis verkopen zonder gedoe",
  "huis verkopen bij emigratie",
  "woning verkopen bij echtscheiding",
  "huis verkopen voor contant geld",
  "huis direct verkopen",
  "woning verkopen aan opkoper",
  "huis verkopen zonder kosten",
  "woning verkopen bij overlijden",
  "huis verkopen bij financiële problemen",
  "huis verkopen aan vastgoedbedrijf",
  "huis verkopen via verkoopuwhuis.nu",
  "direct bod op huis ontvangen",
  "woning verkopen zonder voorbehoud",
  "huis verkopen zonder makelaarskosten",
  "huis opkopen bij scheiding",
  "huis verkopen met achterstallig onderhoud",
  "woning verkopen bij verhuizen naar zorginstelling",
  "huis verkopen binnen 7 dagen",
  "huis verkopen via woningopkoper",
  "huis verkopen zonder notariskosten",
  "woning verkopen bij werkloosheid",
  "huis verkopen bij faillissement",
  "huis verkopen met huurders",
  "woning snel verkopen zonder makelaar",
  "huis verkopen met overwaarde",
  "huis verkopen bij relatiebreuk",
  "huis verkopen voor senioren",
  "woning verkopen als investering",
  "huis verkopen bij gedwongen verkoop",
  "woning verkopen via specialist",
  "huis verkopen zonder stress",
  "huis verkopen bij dubbele lasten",
  "woning verkopen zonder tussenkomst makelaar",
  "huis verkopen bij ontslag",
  "woning snel verkopen voor cash",
  "huis verkopen zonder woningpresentatie",
  "huis verkopen met erfbelasting",
  "huis verkopen en terughuren",
  "woning verkopen bij scheiding met kinderen",
  "huis verkopen bij pensioen",
  "woning verkopen bij verandering in gezinssituatie",
  "huis verkopen bij dreigende executie"
]
