name: dagelijks sitemap update

on:
  schedule:
    - cron: "0 7 * * *" # Dagelijks om 08:00 NL zomertijd (06:00 UTC)
  workflow_dispatch:

jobs:
  trigger-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: POST naar sitemap API
        run: |
          curl -X POST https://verkoopuwhuis.nu/api/sitemap \
            -H "Content-Type: application/json" \
            -d '{}'
